apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-frontend-to-backend-only
  namespace: tenant-a
spec:
  endpointSelector:
    matchLabels:
      app: backend-service
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: frontend-service
  egress:
    - toEndpoints:
      - matchLabels:
          app: frontend-service